source :rubygems

gemspec

group :development do
#  gem 'ruby-debug19', :platform => :mri
#  gem 'ruby-debug-base19', '>=0.11.26'
#  gem 'linecache19', '>=0.5.13'
end

platform :mri do
  gem 'simplecov', :require => false, :group => :test
end

