require 'bundler/gem_tasks'
require 'jaribio/formatter/version'
require 'rspec/core'
require 'rspec/core/rake_task'

#  gem.name = "jaribio-formatter"
#  gem.version = version
#  gem.homepage = "https://github.com/bithckr/Jaribio/tree/master/jaribio-formatter"
#  gem.license = "MIT"
#  gem.summary = %Q{Jaribio test framework formatters}
#  gem.description = %Q{Provide the necessary code to record execution results in Jaribio while running tests in RSpec, Test::Unit, or Cucumber}
#  gem.email = "cbjones1@gmail.com"
#  gem.authors = ["bjones"]

RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = FileList['spec/**/*_spec.rb']
end

task :default => :spec

require 'rdoc/task'
Rake::RDocTask.new do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "jaribio_formatter #{Jaribio::Formatter::VERSION}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

# Disabling some tasks we can't/don't want to ever run
task(:release).clear_prerequisites.clear_actions
