source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'mysql2', '~> 0.2.6'
gem 'devise', '~> 1.4.2'
gem 'jquery-rails', '>= 1.0.12'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'forgery'
end
