source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'jquery-rails'
gem 'mysql2', '~> 0.3.2'
gem 'devise', '~> 1.4.2'
gem 'kaminari'
gem 'foreigner'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

group :development, :test do
  gem 'rake', '>= 0.9.2.2'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'forgery'
  # requires libffi on osx (sudo port install libffi)
  gem 'capybara'
end

gem 'simplecov', :require => false, :group => :test
