source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'jquery-rails'
gem 'devise', '~> 1.4.2'
gem 'kaminari'
gem 'foreigner'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier',     '>= 1.0.3'
end

group :development, :test do
  gem 'rake', '>= 0.9.2.2'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'forgery'
  # requires libffi on osx (sudo port install libffi)
  gem 'capybara'
end


platform :mri do
  gem 'mysql2', '~> 0.3.2'
  gem 'simplecov', :require => false, :group => :test
end

platform :jruby do
  gem 'jruby-openssl'
  gem 'activerecord-jdbcmysql-adapter'

  group :assets do
    gem 'therubyrhino'
  end
end

