require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PreStepsController do

  # This should return the minimal set of attributes required to create a valid
  # PreStep. As you add validations to PreStep, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all pre_steps as @pre_steps" do
      pre_step = PreStep.create! valid_attributes
      get :index
      assigns(:pre_steps).should eq([pre_step])
    end
  end

  describe "GET show" do
    it "assigns the requested pre_step as @pre_step" do
      pre_step = PreStep.create! valid_attributes
      get :show, :id => pre_step.id
      assigns(:pre_step).should eq(pre_step)
    end
  end

  describe "GET new" do
    it "assigns a new pre_step as @pre_step" do
      get :new
      assigns(:pre_step).should be_a_new(PreStep)
    end
  end

  describe "GET edit" do
    it "assigns the requested pre_step as @pre_step" do
      pre_step = PreStep.create! valid_attributes
      get :edit, :id => pre_step.id
      assigns(:pre_step).should eq(pre_step)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PreStep" do
        expect {
          post :create, :pre_step => valid_attributes
        }.to change(PreStep, :count).by(1)
      end

      it "assigns a newly created pre_step as @pre_step" do
        post :create, :pre_step => valid_attributes
        assigns(:pre_step).should be_a(PreStep)
        assigns(:pre_step).should be_persisted
      end

      it "redirects to the created pre_step" do
        post :create, :pre_step => valid_attributes
        response.should redirect_to(PreStep.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pre_step as @pre_step" do
        # Trigger the behavior that occurs when invalid params are submitted
        PreStep.any_instance.stub(:save).and_return(false)
        post :create, :pre_step => {}
        assigns(:pre_step).should be_a_new(PreStep)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PreStep.any_instance.stub(:save).and_return(false)
        post :create, :pre_step => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pre_step" do
        pre_step = PreStep.create! valid_attributes
        # Assuming there are no other pre_steps in the database, this
        # specifies that the PreStep created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PreStep.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => pre_step.id, :pre_step => {'these' => 'params'}
      end

      it "assigns the requested pre_step as @pre_step" do
        pre_step = PreStep.create! valid_attributes
        put :update, :id => pre_step.id, :pre_step => valid_attributes
        assigns(:pre_step).should eq(pre_step)
      end

      it "redirects to the pre_step" do
        pre_step = PreStep.create! valid_attributes
        put :update, :id => pre_step.id, :pre_step => valid_attributes
        response.should redirect_to(pre_step)
      end
    end

    describe "with invalid params" do
      it "assigns the pre_step as @pre_step" do
        pre_step = PreStep.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PreStep.any_instance.stub(:save).and_return(false)
        put :update, :id => pre_step.id, :pre_step => {}
        assigns(:pre_step).should eq(pre_step)
      end

      it "re-renders the 'edit' template" do
        pre_step = PreStep.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PreStep.any_instance.stub(:save).and_return(false)
        put :update, :id => pre_step.id, :pre_step => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pre_step" do
      pre_step = PreStep.create! valid_attributes
      expect {
        delete :destroy, :id => pre_step.id
      }.to change(PreStep, :count).by(-1)
    end

    it "redirects to the pre_steps list" do
      pre_step = PreStep.create! valid_attributes
      delete :destroy, :id => pre_step.id
      response.should redirect_to(pre_steps_url)
    end
  end

end
